title: Change Note Visibility
description: This Add-On will allow you to change the visibility of all notes on documents in the query/selection. Only works on documents you own.
instructions: ''
type: object
documents:
  - query
  - selected
properties:
  access_level:
    title: Access level
    type: string
    description: Public, private, or organization.
    default: public
required: 
  - access_level
categories:
  - bulk
version: 2
